### ISSUE TITLE
Driver connect to all replicas even non-reachable and fails

### ISSUE THREAD

**Issue by necromant2005** [mongodb/mongo-php-driver#461]
### Description
Driver connects all replicas that gets from rs.status() and fails if one of the nodes is not available

### Environment

PHP: 7.0.7  / 7.0.13
OS: mac os x 10.12.1  / ubuntu 16.04 / ubuntu 16.10
```
php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php/7.0/cli/conf.d/mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.1.10-dev
mongodb stability => devel
libmongoc version => 1.3.6
libbson version => 1.3.6
mongodb.debug => no value => no value
```
### Test Script

If possible, attach a complete PHP script that can be excuted on its own to
reproduce the issue. Clarify whether this script can be run from the CLI or if
it can only be reproduced through a web SAPI.

```
<?php
$hosts = [
    'compose_primary_1:27000',
    'compose_secondary1_1:27001',
    'compose_secondary2_1:27002',
];

$manager = new MongoDB\Driver\Manager('mongodb://' . join(',', $hosts) . '/?readPreference=secondary&replicaSet=test');
var_dump($manager->executeQuery('test.ping', new MongoDB\Driver\Query([])));
```

php -v mongo.php
```
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php:9
Stack trace:
#0 /private/var/www/tt/tmp/compose/mongo.php(9): MongoDB\Driver\Manager->executeQuery('test.ping', Object(MongoDB\Driver\Query))
#1 {main}
  thrown in /private/var/www/tt/tmp/compose/mongo.php on line 9

Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php on line 9

MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php on line 9

Call Stack:
    0.0024     356656   1. {main}() /private/var/www/tt/tmp/compose/mongo.php:0
    0.0048     378528   2. MongoDB\Driver\Manager->executeQuery() /private/var/www/tt/tmp/compose/mongo.php:9
```

docker-compose.yml
```
version: '2'
services:
  primary:
    image: mongo
    ports:
      - "27000:27017"
    networks:
      - back-tier
    command: mongod --smallfiles --replSet test
  secondary1:
    image: mongo
    ports:
      - "27001:27017"
    networks:
      - back-tier
    command: mongod --smallfiles --replSet test
  secondary2:
    image: mongo
    ports:
      - "27002:27017"
    networks:
      - back-tier
    command: mongod --smallfiles --replSet test
networks:
  back-tier:
    driver: bridge
```

rs.status()
```
{
	"set" : "test",
	"date" : ISODate("2016-11-21T08:35:18.966Z"),
	"myState" : 1,
	"term" : NumberLong(1),
	"heartbeatIntervalMillis" : NumberLong(2000),
	"members" : [
		{
			"_id" : 0,
			"name" : "88b2ffd96488:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 3007,
			"optime" : {
				"ts" : Timestamp(1479714504, 1),
				"t" : NumberLong(1)
			},
			"optimeDate" : ISODate("2016-11-21T07:48:24Z"),
			"electionTime" : Timestamp(1479714400, 2),
			"electionDate" : ISODate("2016-11-21T07:46:40Z"),
			"configVersion" : 6,
			"self" : true
		},
		{
			"_id" : 1,
			"name" : "compose_secondary1_1:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2884,
			"optime" : {
				"ts" : Timestamp(1479714504, 1),
				"t" : NumberLong(1)
			},
			"optimeDate" : ISODate("2016-11-21T07:48:24Z"),
			"lastHeartbeat" : ISODate("2016-11-21T08:35:17.233Z"),
			"lastHeartbeatRecv" : ISODate("2016-11-21T08:35:17.453Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "88b2ffd96488:27017",
			"configVersion" : 6
		},
		{
			"_id" : 2,
			"name" : "compose_secondary2_1:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2879,
			"optime" : {
				"ts" : Timestamp(1479714504, 1),
				"t" : NumberLong(1)
			},
			"optimeDate" : ISODate("2016-11-21T07:48:24Z"),
			"lastHeartbeat" : ISODate("2016-11-21T08:35:17.233Z"),
			"lastHeartbeatRecv" : ISODate("2016-11-21T08:35:17.453Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "compose_secondary1_1:27017",
			"configVersion" : 6
		},
		{
			"_id" : 3,
			"name" : "compose_secondary:27777",
			"health" : 0,
			"state" : 8,
			"stateStr" : "(not reachable/healthy)",
			"uptime" : 0,
			"optime" : {
				"ts" : Timestamp(0, 0),
				"t" : NumberLong(-1)
			},
			"optimeDate" : ISODate("1970-01-01T00:00:00Z"),
			"lastHeartbeat" : ISODate("2016-11-21T08:35:17.496Z"),
			"lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "HostUnreachable",
			"configVersion" : -1
		}
	],
	"ok" : 1
}
```

/etc/hosts on host machine
```
127.0.0.1 compose_secondary1_1,compose_secondary2_1,compose_primary_1,compose_secondary
```

### Expected and Actual Behavior
Connect only available / live replicas, otherwise failing one of more nodes blocks application data processing, because of connection failure. it must works the same as mongo-cli console

```
test:PRIMARY> db.ping.insert({'pong':1})
WriteResult({ "nInserted" : 1 })
test:PRIMARY> db.ping.findOne()
{ "_id" : ObjectId("5832b424ecfd4c79080880db"), "pong" : 1 }
test:PRIMARY>
```

### Debug Log

php mongo.php
```
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php:9
Stack trace:
#0 /private/var/www/tt/tmp/compose/mongo.php(9): MongoDB\Driver\Manager->executeQuery('test.ping', Object(MongoDB\Driver\Query))
#1 {main}
  thrown in /private/var/www/tt/tmp/compose/mongo.php on line 9

Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php on line 9

MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '88b2ffd96488:27017': php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known] [Failed connecting to 'compose_secondary:27777': Connection refused] in /private/var/www/tt/tmp/compose/mongo.php on line 9

Call Stack:
    0.0024     356656   1. {main}() /private/var/www/tt/tmp/compose/mongo.php:0
    0.0048     378528   2. MongoDB\Driver\Manager->executeQuery() /private/var/www/tt/tmp/compose/mongo.php:9
```

docker compose logs
```
primary_1     | 2016-11-21T08:47:16.142+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to compose_secondary:27017; HostUnreachable: HostUnreachable
primary_1     | 2016-11-21T08:47:16.143+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to compose_secondary:27017
primary_1     | 2016-11-21T08:47:16.157+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to compose_secondary:27017 - HostUnreachable: HostUnreachable
primary_1     | 2016-11-21T08:47:16.157+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to compose_secondary:27017; HostUnreachable: HostUnreachable
secondary2_1  | 2016-11-21T08:47:16.740+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to compose_secondary:27017
secondary2_1  | 2016-11-21T08:47:16.756+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to compose_secondary:27017 - HostUnreachable: HostUnreachable
secondary2_1  | 2016-11-21T08:47:16.756+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to compose_secondary:27017; HostUnreachable: HostUnreachable
secondary2_1  | 2016-11-21T08:47:16.756+0000 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to compose_secondary:27017
```

**Comment by necromant2005** [comment]
my bug in configuration.
correct docker-composer.yml
```
version: '2'
services:
  primary:
    image: mongo
    ports:
      - "27000:27000"
    networks:
      - back-tier
    hostname: compose_primary_1
    command: mongod --port 27000 --smallfiles --replSet test
  secondary1:
    image: mongo
    ports:
      - "27001:27001"
    networks:
      - back-tier
    hostname: compose_secondary1_1
    command: mongod --port 27001 --smallfiles --replSet test
  secondary2:
    image: mongo
    ports:
      - "27002:27002"
    networks:
      - back-tier
    hostname: compose_secondary2_1
    command: mongod --port 27002 --smallfiles --replSet test
networks:
  back-tier:
    driver: bridge
```
